- name: demo
  hosts: all
  gather_facts: false
  tasks:

    - name: ansible version
      debug:
        var: ansible_version

    - name: get modules
      command: pip list
      register: pip

    - name: show modules
      debug:
        var: pip.stdout_lines


